/*
 * 
 * Created by Yuji Nishioka
 * 
 * 
 */

package aula14;

public class Doc {
	/* id is a int attribute */
	private int id;
		
	/* text is a String attribute */
	private String nome;

	/* nota is a float attribute */
	private float nota;

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the nome
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * @param nome the nome to set
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * @return the nota
	 */
	public float getNota() {
		return nota;
	}

	/**
	 * @param nota the nota to set
	 */
	public void setNota(float nota) {
		this.nota = nota;
	}

	/**
	 * @param id
	 * @param nome
	 * @param nota
	 */
	public Doc(int id, String nome, float nota) {
		this.id = id;
		this.nome = nome;
		this.nota = nota;
	}

	/* 
	 * @param n - generated by user
	 */
	public void cubo(int n) {
		System.out.println("Cubo: " + Math.pow(n, 3));
	}
}
